"""CLI: regeneration-equivalence check for the amplifier-data floor pilot.

Runs the amplifier-data E1 guarantee against REAL CI session files, offline and
read-only: it loads every line of an ``events.jsonl``, mirrors it into an
``AmplifierStore`` as a content-addressed Cell, optionally closes+reopens the
durable store (restart / torn-tail survival), regenerates every cell, and reports
whether the regenerated bytes are identical to the source.

This is the "compare its regenerated view against events.jsonl" half of the
pilot — it needs no running session and never enables the hook's hot path.

Usage:
    python -m amplifier_module_hook_context_intelligence.pilot_verify \\
        ~/.amplifier/projects/<slug>/sessions/<id>/context-intelligence/events.jsonl

    # durable restart check (writes a throwaway store file, then reopens it):
    python -m amplifier_module_hook_context_intelligence.pilot_verify <path> \\
        --store-path /tmp/ci-pilot.store --test-restart

Exit code is 0 when regeneration is byte-identical, 1 otherwise (or on no data).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from amplifier_module_hook_context_intelligence.amplifier_data_pilot import verify_events_jsonl


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "path",
        help="Path to an events.jsonl file, or a session dir containing one.",
    )
    parser.add_argument(
        "--store-path",
        default=None,
        help="Optional durable store path. Required for --test-restart.",
    )
    parser.add_argument(
        "--test-restart",
        action="store_true",
        help="Close and reopen the durable store before regeneration (E1 restart check).",
    )
    args = parser.parse_args(argv)

    if args.test_restart and not args.store_path:
        parser.error("--test-restart requires --store-path")

    report = verify_events_jsonl(
        args.path,
        store_path=args.store_path,
        test_restart=args.test_restart,
    )
    print(json.dumps({"source": str(Path(args.path)), **report.as_dict()}, indent=2))
    return 0 if report.byte_identical else 1


if __name__ == "__main__":
    sys.exit(main())
